name: bemeow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  flutter_svg: ^2.2.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  image_picker: ^1.1.2
  google_sign_in: ^7.0.0
  flutter_typeahead: ^5.2.0
  device_info_plus: ^11.5.0
  firebase_storage: ^12.4.9
  cached_network_image: ^3.4.1
  firebase_database: ^11.3.9
  go_router: ^16.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  provider: ^6.1.5
  font_awesome_flutter: ^10.8.0
  audioplayers: ^6.5.0
  just_audio: ^0.10.4
  flutter_soloud: ^3.2.2
  loading_indicator: ^3.1.1
  just_waveform: ^0.0.7
  flutter_riverpod: ^2.6.1
  flutter_audio_waveforms: ^1.2.1+8
  audio_waveforms: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/materialicons-regular.otf
  assets:
    - assets/
    - assets/backgrounds/desktop/
    - assets/backgrounds/mobile/
    - assets/backgrounds/tablet/
    - assets/icons/
    - assets/icons/svg/
    - assets/logos/svg/
    - assets/defaults/avatar.png
    - assets/defaults/cover_thumb.png
    - assets/defaults/cover.png
    - assets/defaults/waveform.svg
    - assets/misc/svg/
    - assets/sounds/
  